// restclient.js 0.1.1
// (c) 2012 Enrique Ponce de Leon, Qennix
// RestClient.js may be distributed under the MIT license.
// For all details and documentation:
// http://qennix.github.com/restclient
(function(){var f=this._;!f&&"undefined"!==typeof require&&(f=require("underscore"));var d;d="undefined"!==typeof exports?exports:this.RestClient={};d.VERSION="0.1.1";d.reset=function(){this.authorization={};this.server={};this.body={};this.headers={};return this};d.useRelativeURL=!1;d.needsAuthorization=!0;d.$=this.jQuery;d.RESTMethods={create:"POST",read:"GET",update:"PUT","delete":"DELETE"};d.OAUTH2GrantTypes={code:"authorization_code",implicit:"token",user:"password",client:"client_credentials",
refresh:"refresh_token"};d.setClient=function(a,c,e){this.authorization.client_id=a;this.authorization.client_secret=c;this.authorization.client_url="undefined"!==e?e:null;return this};d.setGrantType=function(a,c){this.authorization.grant_type="undefined"!==this.OAUTH2GrantTypes[a]?this.OAUTH2GrantTypes[a]:null;this.authorization=f.extend(this.authorization,c);return this};d.setServerUrl=function(a){this.server.rest_url="undefined"!==a?a:null;this.useRelativeURL=!0};d.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
encode:function(a){for(var c="",e,b,d,h,i,g,f=0,a=this._utf8_encode(a);f<a.length;)e=a.charCodeAt(f++),b=a.charCodeAt(f++),d=a.charCodeAt(f++),h=e>>2,e=(e&3)<<4|b>>4,i=(b&15)<<2|d>>6,g=d&63,isNaN(b)?i=g=64:isNaN(d)&&(g=64),c=c+this._keyStr.charAt(h)+this._keyStr.charAt(e)+this._keyStr.charAt(i)+this._keyStr.charAt(g);return c},decode:function(a){for(var c="",e,b,d,h,f,g=0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<a.length;)e=this._keyStr.indexOf(a.charAt(g++)),b=this._keyStr.indexOf(a.charAt(g++)),
h=this._keyStr.indexOf(a.charAt(g++)),f=this._keyStr.indexOf(a.charAt(g++)),e=e<<2|b>>4,b=(b&15)<<4|h>>2,d=(h&3)<<6|f,c+=String.fromCharCode(e),64!==h&&(c+=String.fromCharCode(b)),64!==f&&(c+=String.fromCharCode(d));return c=this._utf8_decode(c)},_utf8_encode:function(a){for(var a=a.replace(/\r\n/g,"\n"),c="",e=0;e<a.length;e++){var b=a.charCodeAt(e);128>b?c+=String.fromCharCode(b):(127<b&&2048>b?c+=String.fromCharCode(b>>6|192):(c+=String.fromCharCode(b>>12|224),c+=String.fromCharCode(b>>6&63|128)),
c+=String.fromCharCode(b&63|128))}return c},_utf8_decode:function(a){for(var c="",e=0,b=0,d=0,f=0;e<a.length;)b=a.charCodeAt(e),128>b?(c+=String.fromCharCode(b),e++):191<b&&224>b?(d=a.charCodeAt(e+1),c+=String.fromCharCode((b&31)<<6|d&63),e+=2):(d=a.charCodeAt(e+1),f=a.charCodeAt(e+2),c+=String.fromCharCode((b&15)<<12|(d&63)<<6|f&63),e+=3);return c}};d.setAuthorizationMode=function(a){this.needsAuthorization=a?a:!0;return this};d.proxy=function(){return d.$.ajax.apply(d.$,arguments)};d.consume=function(a,
c,e,b){a={type:this.RESTMethods[a],dataType:"json"};a.url=c.url?c.url:this.server.rest_url;if("undefined"!==b?b:1)b=this.Base64.encode(this.authorization.client_id+":"+this.authorization.client_secrect),this.headers.Authorization="Basic "+b;b={};if(this.authorization.grant_type)switch(b.grant_type=this.authorization.grant_type,this.authorization.grant_type){case "authorization_code":b.code=this.authorization.code;break;case "token":b.token=this.authorization.token;break;case "password":b.username=
this.authorization.username;b.password=this.authorization.password;break;case "client_credentials":b.client_id=this.authorization.client_id;b.client_id=this.authorization.client_secret;break;case "refresh_token":b.refresh_token=this.authorization.refresh_token}b.apply(this,c.data);a.data=b;a.headers=this.headers;a.success=e;return d.proxy(f.extend(a,c))};d.sync=function(){return this}}).call(this);
