// restclient.js 0.1.1
// (c) 2012 Enrique Ponce de Leon, Qennix
// RestClient.js may be distributed under the MIT license.
// For all details and documentation:
// http://qennix.github.com/restclient
(function(){var f=this._;!f&&"undefined"!==typeof require&&(f=require("underscore"));var d;d="undefined"!==typeof exports?exports:this.RestClient={};d.VERSION="0.1.1";d.reset=function(){this.authorization={};this.server={};this.body={};this.headers={};return this};d.needsAuthorization=!0;d.$=this.jQuery;d.RESTMethods={create:"POST",read:"GET",update:"PUT","delete":"DELETE"};d.OAUTH2GrantTypes={code:"authorization_code",implicit:"token",user:"password",client:"client_credentials",refresh:"refresh_token"};
d.setClient=function(a,b,e){this.authorization.client_id=a;this.authorization.client_secret=b;this.authorization.client_url="undefined"!==e?e:null;return this};d.setGrantType=function(a,b){this.authorization.grant_type="undefined"!==this.OAUTH2GrantTypes[a]?this.OAUTH2GrantTypes[a]:null;this.authorization=f.extend(this.authorization,b);return this};d.setAuthorizationServer=function(a){var b=!0;"undefined"===typeof a||null===a?b=!1:a.match(/(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/)?
this.server.rest_auth_uri=a:b=!1;return b};d.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){for(var b="",e,c,d,h,i,g,f=0,a=this._utf8_encode(a);f<a.length;)e=a.charCodeAt(f++),c=a.charCodeAt(f++),d=a.charCodeAt(f++),h=e>>2,e=(e&3)<<4|c>>4,i=(c&15)<<2|d>>6,g=d&63,isNaN(c)?i=g=64:isNaN(d)&&(g=64),b=b+this._keyStr.charAt(h)+this._keyStr.charAt(e)+this._keyStr.charAt(i)+this._keyStr.charAt(g);return b},decode:function(a){for(var b="",e,c,d,h,f,g=
0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<a.length;)e=this._keyStr.indexOf(a.charAt(g++)),c=this._keyStr.indexOf(a.charAt(g++)),h=this._keyStr.indexOf(a.charAt(g++)),f=this._keyStr.indexOf(a.charAt(g++)),e=e<<2|c>>4,c=(c&15)<<4|h>>2,d=(h&3)<<6|f,b+=String.fromCharCode(e),64!==h&&(b+=String.fromCharCode(c)),64!==f&&(b+=String.fromCharCode(d));return b=this._utf8_decode(b)},_utf8_encode:function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",e=0;e<a.length;e++){var c=a.charCodeAt(e);128>c?b+=String.fromCharCode(c):
(127<c&&2048>c?b+=String.fromCharCode(c>>6|192):(b+=String.fromCharCode(c>>12|224),b+=String.fromCharCode(c>>6&63|128)),b+=String.fromCharCode(c&63|128))}return b},_utf8_decode:function(a){for(var b="",e=0,c=0,d=0,f=0;e<a.length;)c=a.charCodeAt(e),128>c?(b+=String.fromCharCode(c),e++):191<c&&224>c?(d=a.charCodeAt(e+1),b+=String.fromCharCode((c&31)<<6|d&63),e+=2):(d=a.charCodeAt(e+1),f=a.charCodeAt(e+2),b+=String.fromCharCode((c&15)<<12|(d&63)<<6|f&63),e+=3);return b}};d.setAuthorizationMode=function(a){this.needsAuthorization=
a?a:!0;return this};d.proxy=function(){return d.$.ajax.apply(d.$,arguments)};d.consume=function(a,b,e,c){a={type:this.RESTMethods[a],dataType:"json"};a.url=b.url?b.url:this.server.rest_url;if("undefined"!==c?c:1)c=this.Base64.encode(this.authorization.client_id+":"+this.authorization.client_secrect),this.headers.Authorization="Basic "+c;c={};if(this.authorization.grant_type)switch(c.grant_type=this.authorization.grant_type,this.authorization.grant_type){case "authorization_code":c.code=this.authorization.code;
break;case "token":c.token=this.authorization.token;break;case "password":c.username=this.authorization.username;c.password=this.authorization.password;break;case "client_credentials":c.client_id=this.authorization.client_id;c.client_id=this.authorization.client_secret;break;case "refresh_token":c.refresh_token=this.authorization.refresh_token}c.apply(this,b.data);a.data=c;a.headers=this.headers;a.success=e;return d.proxy(f.extend(a,b))};d.sync=function(){return this}}).call(this);
